-- SwiftDrop merchant drop-off network foundation.
CREATE TABLE IF NOT EXISTS drop_off_locations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), business_id UUID NOT NULL REFERENCES business_accounts(id) ON DELETE CASCADE, name TEXT NOT NULL, address TEXT NOT NULL, latitude NUMERIC(9,6) NOT NULL, longitude NUMERIC(9,6) NOT NULL, phone TEXT NOT NULL, operating_hours JSONB NOT NULL DEFAULT '{}'::jsonb, capacity INTEGER NOT NULL DEFAULT 50 CHECK (capacity > 0 AND capacity <= 10000), commission_minor BIGINT NOT NULL DEFAULT 50000 CHECK (commission_minor >= 0), status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','ACTIVE','SUSPENDED','REJECTED')), verification_status TEXT NOT NULL DEFAULT 'PENDING' CHECK (verification_status IN ('PENDING','VERIFIED','REJECTED')), verified_by_user_id UUID REFERENCES users(id), verified_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_drop_off_locations_status_geo ON drop_off_locations(status, latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_drop_off_locations_business ON drop_off_locations(business_id, status);
CREATE TABLE IF NOT EXISTS drop_off_location_documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), location_id UUID NOT NULL REFERENCES drop_off_locations(id) ON DELETE CASCADE, document_type TEXT NOT NULL CHECK (document_type IN ('BUSINESS_REGISTRATION','PREMISES_EVIDENCE','IDENTITY','OTHER')), storage_key TEXT, document_reference TEXT, status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED')), review_note TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_drop_off_docs_location ON drop_off_location_documents(location_id, status);
CREATE TABLE IF NOT EXISTS drop_off_parcels (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), delivery_id UUID NOT NULL REFERENCES deliveries(id) ON DELETE CASCADE, location_id UUID NOT NULL REFERENCES drop_off_locations(id), endpoint TEXT NOT NULL CHECK (endpoint IN ('PICKUP','DROPOFF')), intake_code TEXT NOT NULL UNIQUE, status TEXT NOT NULL DEFAULT 'EXPECTED' CHECK (status IN ('EXPECTED','AT_LOCATION','READY_FOR_COURIER','COURIER_COLLECTED','COMPLETED','CANCELLED','DISPUTED')), parcel_photo_key TEXT, storage_reference TEXT, received_by_user_id UUID REFERENCES users(id), received_at TIMESTAMPTZ, courier_driver_id UUID REFERENCES drivers(id), courier_collected_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(delivery_id, location_id, endpoint));
CREATE INDEX IF NOT EXISTS idx_drop_off_parcels_location_status ON drop_off_parcels(location_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_drop_off_parcels_delivery ON drop_off_parcels(delivery_id, endpoint);
CREATE TABLE IF NOT EXISTS drop_off_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), parcel_id UUID NOT NULL REFERENCES drop_off_parcels(id) ON DELETE CASCADE, actor_user_id UUID REFERENCES users(id), event_type TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_drop_off_events_parcel_time ON drop_off_events(parcel_id, created_at ASC);
CREATE TABLE IF NOT EXISTS drop_off_commission_ledger (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), location_id UUID NOT NULL REFERENCES drop_off_locations(id), parcel_id UUID NOT NULL REFERENCES drop_off_parcels(id), amount_minor BIGINT NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'NGN', status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','EARNED','AVAILABLE','PAID','REVERSED','DISPUTED')), provider_reference TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(parcel_id));
CREATE INDEX IF NOT EXISTS idx_drop_off_commission_location_status ON drop_off_commission_ledger(location_id, status, created_at DESC);
CREATE TABLE IF NOT EXISTS drop_off_application_audit (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), location_id UUID NOT NULL REFERENCES drop_off_locations(id) ON DELETE CASCADE, actor_user_id UUID NOT NULL REFERENCES users(id), old_status TEXT, new_status TEXT NOT NULL, note TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());